### ISSUE TITLE
Cannot run program "su"

### ISSUE THREAD

**Issue by erderis** [gokul1630/root#6]
I'm getting this error (when the root status result is false):

java.io.IOException: Cannot run program "su": error=2, No such file or directory

at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
at com.stericson.RootTools.execution.Shell.<init>(Shell.java:66)
at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:513)
at com.stericson.RootTools.execution.Shell.startRootShell(Shell.java:495)
at com.stericson.RootTools.internal.RootToolsInternalMethods.isAccessGiven(RootToolsInternalMethods.java:764)
at com.stericson.RootTools.RootTools.isAccessGiven(RootTools.java:538)
at com.gokul.root.RootPlugin.isRooted(RootPlugin.java:51)
at com.gokul.root.RootPlugin.onMethodCall(RootPlugin.java:41)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:942)

**Comment by shivapardheep** [comment]
I am also have a same issue.
